feat:create-pages
2chanhaeng/codingon-kdt-web7-team3-fe pull request #1
Opened 2023-07-04 15:05 UTC by Yerim96

2023-07-04 15:05 UTC, Yerim96 commented
feat:create-pages

2023-07-05 00:32 UTC, 2chanhaeng requested changes
수고하셨습니다! 😊
요청드린 사항과 질문에 대한 답변 부탁드립니다!
추가적으로, 
1. 커밋은 최대한 여러번으로 나눠주세요. 커밋을 여러개로 나눠서 해주시면 제가 예림님의 생각을 이해하기 쉽습니다.
2. 사용하지 않는 파일을 미리 만들어주지 말아주세요. 컨플릭트가 날 가능성이 높아집니다. 
3. 특별한 이유가 없는 경우에는 `div` 태그 보다는 [시멘틱 태그](https://developer.mozilla.org/ko/docs/Glossary/Semantics)를 이용 부탁 드립니다. 코드 가독성이 좋아지는 등 여러가지 이점이 있습니다. [\[HTML\] 시맨틱 태그 (Semantic Tag)란? 🧐](https://velog.io/@syoung125/%EC%8B%9C%EB%A7%A8%ED%8B%B1-%ED%83%9C%EA%B7%B8-Semantic-Tag-%EC%9E%98-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)
4. 특별한 이유가 없는 경우에는 Fragment(`<>...</>`)를 사용하기 보다는 여러개의 컴포넌트로 나누어 사용하기를 권장합니다. 코드 가독성이 좋아집니다.

2023-07-05 00:32 UTC, 2chanhaeng commented on app/page.tsx
> +    <>
빈 Fragment 는 꼭 필요한 경우가 아니라면 사용을 자제해주세요.

2023-07-05 00:32 UTC, 2chanhaeng commented on app/page.tsx
> +      <div>
꼭 `div` 태그를 이용해야할 경우가 아니라면 `div` 태그보다는 시멘틱 태그를 위주로 사용해주세요.

2023-07-05 00:32 UTC, 2chanhaeng commented on app/globals.css
CSS 변수대신 SCSS 변수를 이용하는게 더 편하게 사용할 수 있습니다.
[/styles/variables.module.scss](https://github.com/2chanhaeng/codingon-kdt-web7-team3-fe/blob/main/styles/variables.module.scss)에 정의해 두시면 전역적으로 사용 가능합니다.

2023-07-05 00:32 UTC, 2chanhaeng commented on app/chat/[id]/page.tsx
> +  console.log(params);
사용하지 않는 콘솔 출력 코드는 웬만하면 지워주세요.

2023-07-05 00:32 UTC, 2chanhaeng commented on app/_app.tsx
어디에 사용되는 코드인가요?

2023-07-05 00:32 UTC, 2chanhaeng commented on app/page.tsx
> +import React from "react";
사용하지 않는데 임포트 하신 이유가 있을까요?

2023-07-05 01:39 UTC, Yerim96 commented on app/_app.tsx
사용하지 않는 코드입니다.
제거했습니다.

2023-07-05 02:04 UTC, Yerim96 commented on app/page.tsx
> +      <div>
div 삭제 후 nav 태그로 수정했습니다.

2023-07-05 02:04 UTC, Yerim96 commented on app/page.tsx
> +    <>
빈 Fragment 삭제했습니다.

2023-07-05 02:04 UTC, Yerim96 commented on app/globals.css
사용하지 않는 css 파일 삭제했습니다.

2023-07-05 02:05 UTC, Yerim96 commented on app/chat/[id]/page.tsx
> +  console.log(params);
제거 완료했습니다.

2023-07-05 02:05 UTC, Yerim96 commented on app/page.tsx
> +import React from "react";
삭제 완료했습니다.

2023-07-05 02:12 UTC, 2chanhaeng commented on app/globals.css
해당 파일은 삭제하면 안되는 파일입니다.
[`git checkout`](https://yuja-kong.tistory.com/195) 명령어로 다시 되돌려주세요.
![image](https://github.com/2chanhaeng/codingon-kdt-web7-team3-fe/assets/61987505/0b40a4ee-4b0c-4c54-bb62-c62ca89667d0)

2023-07-05 02:16 UTC, 2chanhaeng requested changes
수고하셨습니다!
`app/globals.css` 파일 복구과 요청되었지만 변경되지 않은 부분 다시 한 번 확인 부탁드립니다.
또한 말씀드렸던 비어있는 사용하지 않는 페이지들도 모두 지워주시면 감사하겠습니다.

2023-07-05 02:16 UTC, 2chanhaeng commented on app/page.tsx
> +import React from "react";
삭제 되지 않았습니다. 다시 한 번 확인 부탁드립니다.

2023-07-05 03:03 UTC, 2chanhaeng approved these changes
수고 많으셨습니다! 👍

2023-07-05 03:04 UTC, merged