Feat/login-pages
2chanhaeng/codingon-kdt-web7-team3-fe pull request #2
Opened 2023-07-04 15:13 UTC by Yerim96

2023-07-04 15:13 UTC, Yerim96 commented
Feat/login-pages

2023-07-05 02:48 UTC, 2chanhaeng requested changes
수고하셨습니다! 😄
질문 드린 사항에 대한 답변 부탁드립니다!

2023-07-05 02:48 UTC, 2chanhaeng commented on app/login/page.tsx
> +
로그인 페이지에 로그아웃 함수가 있는 이유가 있을까요?

2023-07-05 02:48 UTC, 2chanhaeng commented on app/login/page.tsx
> +        <br />
다음부터는 별다른 이유가 없다면 `br` 태그 보다는 `margin` 스타일 속성을 지정해서 사용해주시면 감사하겠습니다.

2023-07-05 02:48 UTC, 2chanhaeng commented on app/login/page.tsx
> +      localStorage.setItem("login", "true");
이 값은 어디에 쓰이는 값인가요?

2023-07-05 03:19 UTC, Yerim96 commented on app/login/page.tsx
> +
로그인 페이지에서 로그아웃 처리를 해주려고 함수를 생성했습니다

2023-07-05 03:20 UTC, Yerim96 commented on app/login/page.tsx
> +      localStorage.setItem("login", "true");
localStorage 말씀하시는건가요??

2023-07-05 03:22 UTC, Yerim96 commented on app/login/page.tsx
> +        <br />
넵 일단 기능이 되는지만 짜놓은 코드라, 간격이나 위치는 추후에 scss로 조정할 예정입니다!

2023-07-05 04:21 UTC, Yerim96 commented on app/login/page.tsx
> +
로그아웃 함수 삭제했습니다

2023-07-05 06:20 UTC, 2chanhaeng requested changes
수고 많으셨습니다! 👍

2023-07-05 06:21 UTC, 2chanhaeng approved these changes

2023-07-05 06:22 UTC, merged