Feat/profiles page
2chanhaeng/codingon-kdt-web7-team3-fe pull request #6
Opened 2023-07-10 12:08 UTC by Yerim96

-프로필 페이지에서 프로필 불러오기
-프로필 페이지에서 생성버튼 
-프로필 페이지/id에서 내 프로필들 불러오기
-프로필페이지/id에  내가 선택한 내 프로필 id의 값 실시간으로 뿌려주기
-프로필 페이지/id에 팔로잉, 팔로우, 태그 목록 불러오기
-프로필 페이지/id에서 선택 id의 글목록 불러오기 
-프로필페이지/id에서 프로필 수정은 미완

2023-07-10 12:55 UTC, 2chanhaeng requested changes
수고하셨습니다! 😄 
컴포넌트, 모듈화에 점점 익숙해지시는 것 같아 다행이에요!
문제가 생겨도 다시 되돌릴 수 있으니 코드를 분리하는 것을 무서워하지 말아주세요.
요청드린 사항 변경 부탁드립니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/_app.tsx
사용하지 않는 파일입니다.
지워주시면 감사하겠습니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/globals.css
사용하지 않을 코드라면 지워주시길 바랍니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/layout.tsx
> +"use client";
지워주시길 바랍니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/[id]/page.tsx
> +  const [followerProfiles, setFollowerProfile] = useState([] as ProfileType[]);
모두 프로필과 관련이 있는 값들이므로 상태 하나로 통합하여 관리하면 더 좋을 것 같습니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/[id]/page.tsx
> +  const [profilePosts, setProfilePosts] = useState([] as ProfileType[]);
해당 상태는 포스트를 관리하는 상태이므로 `ProfileType` 보다는 `PostType` 을 새로 정의해서 만들어주시면 감사하겠습니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/[id]/page.tsx
> +  //유저를 팔로우하고 있는 프로ㅍㄹ을 불러오는 useState
오타 수정해주세요.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/[id]/page.tsx
> +  const [isFollowerModalOpen, setIsFollowerModalOpen] = useState(false);
모달을 열고 닫는 것은 상태가 아닌 CSS 로 하는 것이 보기에 좋습니다.
혹은 [`dialog` 태그](https://developer.mozilla.org/ko/docs/Web/HTML/Element/dialog)를 이용해보세요.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/[id]/page.tsx
> +      // });
사용하지 않는 코드는 지워주시길 바랍니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/[id]/page.tsx
> +      // });
사용하지 않는 코드는 지워주시길 바랍니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/[id]/page.tsx
> +      // });
사용하지 않는 코드는 지워주시길 바랍니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/[id]/page.tsx
> +      // });
사용하지 않는 코드는 지워주시길 바랍니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/[id]/page.tsx
> +      // });
사용하지 않는 코드는 지워주시길 바랍니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/[id]/page.tsx
> +  };
상기한 것처럼 모달을 상태로 관리하는 것은 지양해주시길 바랍니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/[id]/page.tsx
> +      )}
예림님께서 주석으로 나눠놓은 단위만큼 컴포넌트화 하면 딱 알맞을 것 같습니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/page.tsx
> +import { ProfileType, ProfilesData } from "@/types/profile";
사용되지 않고 있는 값들은 지워주시면 감사하겠습니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/page.tsx
> +  );
모두 모달과 관련된 상태라면 하나의 상태로 처리하는 것이 좋을 것 같습니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on app/profile/page.tsx
> +      )}
모달 컴포넌트화 해주시면 감사하겠습니다.
모달 내부 구성 요소들도 적당히 컴포넌트화 하면 더 좋을 것 같습니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on components/Profile/index.tsx
> +}
`interface` 잘 만들어 두셨습니다!
타입도, 함수도, 컴포넌트도, 이런 식으로 코드를 분리하면 됩니다.
코드를 분리하는 것을 두려워하지 말아주세요!

2023-07-10 12:55 UTC, 2chanhaeng commented on components/ProfileId/ProfileInfo.tsx
> +      <p> {id}</p>
`id` 는 보이지 않아도 될 것 같습니다.

2023-07-10 12:55 UTC, 2chanhaeng commented on types/profile.ts
타입 모듈화 정말 잘 해두셨습니다!

2023-07-11 00:08 UTC, Yerim96 commented on app/globals.css
넵 삭제했습니다.

2023-07-11 00:08 UTC, Yerim96 commented on app/layout.tsx
> +"use client";
수정했습니다.

2023-07-11 00:13 UTC, Yerim96 commented on app/profile/[id]/page.tsx
> +  const [profilePosts, setProfilePosts] = useState([] as ProfileType[]);
수정했습니다!

2023-07-11 00:16 UTC, Yerim96 commented on components/ProfileId/ProfileInfo.tsx
> +      <p> {id}</p>
삭제했습니다!

2023-07-11 00:17 UTC, Yerim96 commented on types/profile.ts
감사합니다! ㅎㅎ

2023-07-11 04:56 UTC, Yerim96 commented on app/profile/[id]/page.tsx
> +  //유저를 팔로우하고 있는 프로ㅍㄹ을 불러오는 useState
수정완료

2023-07-11 04:58 UTC, Yerim96 commented on app/profile/[id]/page.tsx
> +      // });
삭제완료

2023-07-11 05:00 UTC, Yerim96 commented on app/profile/page.tsx
> +import { ProfileType, ProfilesData } from "@/types/profile";
삭제완료

2023-07-11 05:19 UTC, Yerim96 commented on app/profile/[id]/page.tsx
> +  const [followerProfiles, setFollowerProfile] = useState([] as ProfileType[]);
완료

2023-07-12 00:18 UTC, merged